version: '3'
services:
    web:
        build: images/apache
        image: flo/tournoi:develop
        volumes:
            - ..:/var/www/floTournoi
        ports:
            - "80:80"
        environment:
            - USER_ID=${USER_ID}
            - GROUP_ID=${GROUP_ID}
