# index:
#    path: /
#    controller: Flo\Tournoi\Controller\DefaultController::index

tournoi_test:
    path: /test
    controller: Flo\Tournoi\Controllers\TestController::index

tournoi_player:
    resource: "routes/tournoi/player.yaml"

tournoi_tournament:
    resource: "routes/tournoi/tournament.yaml"
