# index:
#    path: /
#    controller: Flo\Tournoi\Controller\DefaultController::index

tournoi_home:
    path: /
    controller: Flo\Tournoi\Controllers\HomeController::index

tournoi_player:
    resource: "routes/tournoi/player.yaml"

tournoi_tournament:
    resource: "routes/tournoi/tournament.yaml"

tournoi_stage:
    resource: "routes/tournoi/stage.yaml"
