tournoi_player_view_create:
    path: /player/create
    methods: [GET]
    controller: Flo\Tournoi\Controllers\Player\PlayerController::viewCreate

tournoi_player_create:
    path: /player/create
    methods: [POST]
    controller: Flo\Tournoi\Controllers\Player\PlayerController::create

tournoi_player_list:
    path: /player/list
    methods: [GET]
    controller: Flo\Tournoi\Controllers\Player\PlayerController::list

tournoi_player_remove:
    path: /player/remove/{uuid}
    methods: [GET]
    controller: Flo\Tournoi\Controllers\Player\PlayerController::remove
