tournoi_tournament_list:
    path: /tournament/list
    methods:  [GET]
    controller: Flo\Tournoi\Controllers\Tournament\TournamentController::displayList

tournoi_tournament_remove:
    path: /tournament/remove/{uuid}
    methods: [GET]
    controller: Flo\Tournoi\Controllers\Tournament\TournamentController::remove

tournoi_tournament_show:
    path: /tournament/{uuid}
    methods: [GET]
    controller: Flo\Tournoi\Controllers\Tournament\TournamentController::show
